'use strict'

// API_ERROR
export const SET_APP_ERROR = 'SET_APP_ERROR'
export const UNSET_APP_ERROR = 'UNSET_APP_ERROR'

// SIGN_UP
export const SIGN_UP_START = 'SIGN_UP_START'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'

// LOG_IN
export const LOG_IN_START = 'LOG_IN_START'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'

// CURRENT_USER
export const CURRENT_USER_FETCH_START = 'CURRENT_USER_FETCH_START'
export const CURRENT_USER_FETCH_SUCCESS = 'CURRENT_USER_FETCH_SUCCESS'
export const CURRENT_USER_FETCH_ERROR = 'CURRENT_USER_FETCH_ERROR'

// CERTIFY_SOMEONE
export const CERTIFY_SOMEONE_START = 'CERTIFY_SOMEONE_START'
export const CERTIFY_SOMEONE_SUCCESS = 'CERTIFY_SOMEONE_SUCCESS'
export const CERTIFY_SOMEONE_ERROR = 'CERTIFY_SOMEONE_ERROR'

export const CERTIFY_STATE_NOT_STARTED = 'CERTIFY_STATE_NOT_STARTED'
export const CERTIFY_STATE_STARTED = 'CERTIFY_STATE_STARTED'
export const CERTIFY_STATE_SUCCESS = 'CERTIFY_STATE_SUCCESS'
export const CERTIFY_STATE_FAILED = 'CERTIFY_STATE_FAILED'

export const CERTIFY_RECEIVER_USERNAME_SEARCH_RESULTS = 'CERTIFY_RECEIVER_USERNAME_SEARCH_RESULTS'